### ISSUE TITLE
Broken support for older LLVM

### ISSUE THREAD

**Issue by dkfellows** [dkfellows/llvmtcl#19]
Describe the problem
--------------------
Code currently fails to build with LLVM 3.8 (3.9 is unsupported because of other crippling bugs) and 4.0 gives worrying warnings:
<pre>
./generic/llvmtcl.cpp:83:45: warning: address of 'os' will always evaluate to
      'true' [-Wpointer-bool-conversion]
            objc, argv.data(), "called from Tcl", &os);
                                                   ^~
./generic/llvmtcl.cpp:544:46: warning: reference cannot be bound to dereferenced
      null pointer in well-defined C++ code; pointer may be assumed to always
      convert to true [-Wundefined-bool-conversion]
        Tcl_ListObjAppendElement(NULL, rtl, NewObj(&value));
                                            ~~~~~~  ^~~~~
</pre>
5.0 and 6.0 both compile cleanly. I plan on dropping 3.* entirely (as it doesn't support the coroutine analysis and optimisation header), and fixing 4.0.

**Comment by kennykb** [comment]
I'm totally fine with dropping 3.x support. Even on my Ubuntu LTS machines, I rolled forward to 5.0 a while ago. I have tried testing LLVM 7. There are further incompatible (combat-able?) API changes that I haven't had time to investigate. Since 6 is the current stable release, it's not worth holding up an llvmtcl release for them.

**Comment by dkfellows** [comment]
Fixed
