### ISSUE TITLE
llvmtcl doesn't build against llvm 5.0

### ISSUE THREAD

**Issue by kennykb** [dkfellows/llvmtcl#4]
Attached file has the make log.

API stability would be a wonderful thing.

[make.output.txt](https://github.com/dkfellows/llvmtcl/files/1413280/make.output.txt)

**Comment by dkfellows** [comment]
The biggest problem with LLVM is that they don't seem to believe in API stability.

**Comment by dkfellows** [comment]
That branch isn't working yet. It builds cleanly, and crashes silently when I test it properly.

**Comment by dkfellows** [comment]
It turns out that the problem there was a change to the definitions of the `llvm.lifetime.start` and `llvm.lifetime.end` intrinsics, which both [sprouted an extra type argument](https://github.com/llvm-mirror/llvm/commit/bdbe8280f25339054c5314e87e4ddfa844c71014). Which is _undocumented_. Nice!

I've enhanced the code to parse the intrinsic definitions so that we can be sure in future that we will not have silent crashes any more, but rather nice Tcl errors instead that describe the actual problem.

**Comment by dkfellows** [comment]
Fixed. NB: the changes to the intrinsics mean that alterations to downstream code may be required (i.e., will definitely be for tclquadcode; I've committed that change already).
